### ISSUE TITLE
react-icons-kit@1.0.7 requires a peer of react@^15

### ISSUE THREAD

**Issue by drpefr** [wmira/react-icons-kit#18]

**Comment by wmira** [comment]
@drpefr  what version of react are you using?

**Comment by paschaldev** [comment]
@wmira I use react 16. I got the same warning

**Comment by wmira** [comment]
@paschaldev  i changed peerDependency to react >=15. Should not give you warnings now.

**Comment by wmira** [comment]
updated version to 1.1.2

**Comment by wmira** [comment]
Thanks. Closing.
