### ISSUE TITLE
Add Feather Icons

### ISSUE THREAD

**Issue by JPStrydom** [wmira/react-icons-kit#20]
It would be awesome if this package could include [FeatherIcons](https://feathericons.com/).

**Comment by wmira** [comment]
this should be in next release this week.

**Comment by JPStrydom** [comment]
That's fantastic! Glad to hear.

**Comment by wmira** [comment]
@JPStrydom this has been completed. The new site should have the icons http://wmira.github.io/react-icons-kit/index.html  and 1.1.4 has been published.

I'm closing this now.
