### ISSUE TITLE
horizontalCenter in Bootstrap button not working

### ISSUE THREAD

**Issue by HamadaBrest** [wmira/react-icons-kit#22]
```
import { Button } from 'reactstrap'
import Icon, { horizontalCenter } from 'react-icons-kit';
import { ic_looks_one } from 'react-icons-kit/md/ic_looks_one'

const MyButton = horizontalCenter(props => <Button>{props.children}</Button>)

<MyButton>
hello world   <Icon icon={ic_looks_one} />
</Mybutton>
```

**Comment by wmira** [comment]
@HamadaBrest good that you have it worked out. Will take a look at this again. Usually you need to wrap the items with some something that would center the content. I will be deprecating the horizontalCenter and be replacing it something much less confusing to use.

Closing for now.
