### ISSUE TITLE
DOM property warnings

### ISSUE THREAD

**Issue by piotrzaborow** [wmira/react-icons-kit#27]
SvgIcon uses wrong React prop. Instead of stroke-width, stroke-linecap, stroke-linejoin, should be used strokeWidth, strokeLinecap, strokeLinejoin.

<img width="721" alt="screen shot 2018-05-17 at 13 41 15" src="https://user-images.githubusercontent.com/5574918/40175344-16a9d5d0-59d8-11e8-90c7-e8083f687994.png">

**Comment by wmira** [comment]
@piotrzaborow thanks for the report. Fixed in 1.1.5 and added test case
