### ISSUE TITLE
display inline-flex issue

### ISSUE THREAD

**Issue by Mujaddadi** [wmira/react-icons-kit#32]
I am not sure why you used `display:inline-flex` but it doesn't make Icons align well if I used inside other element, for example in the below screenshots, it is placed inside h1 and you can see the default alignment. it's a bit upward

![domacare 2 0 beta](https://user-images.githubusercontent.com/2556882/46490187-0264ea00-c810-11e8-9f50-867ab2a8d04e.png)

Instead if you have used  `display:inline-block` it would fit very well

![domacare 2 0 beta 1](https://user-images.githubusercontent.com/2556882/46490266-36d8a600-c810-11e8-853d-9e5bfd54c29c.png)

So I have to change it every time `display:inline-block`.

**Comment by Mujaddadi** [comment]
Thanks and good to know that you are working on it.

**Comment by wmira** [comment]
@Mujaddadi this has been updated on the latest release 1.2.0
