### ISSUE TITLE
react-icons-kit website page refresh giving 404

### ISSUE THREAD

**Issue by Mujaddadi** [wmira/react-icons-kit#36]
I think you need to add redirection rules for the URLs used in react-icons-kit website because the refreshing of any page giving 404
http://wmira.github.io/react-icons-kit/guide

![screenshot 1](https://user-images.githubusercontent.com/2556882/48774661-8c3f1880-ecd3-11e8-9141-706a52922880.png)

**Comment by wmira** [comment]
Thanks. I will update such that it will hash link to index.html

Cheers,
Warren

**Comment by wmira** [comment]
closing this now
