### ISSUE TITLE
Update Material Design Icons to 4.0.0

### ISSUE THREAD

**Issue by lyleunderwood** [wmira/react-icons-kit#59]
[Version 4.0.0 was released](https://github.com/google/material-design-icons/releases/tag/4.0.0) at the end of August and it has icons that the current 3.0.1 is missing. I was trying to find [`calendar_today`](https://github.com/google/material-design-icons/tree/master/src/action/calendar_today), for example, but it doesn't exist in 3.0.1.

**Comment by wmira** [comment]
Hi @lyleunderwood thanks and appreciate the PR, will check this and publish around weekend.
