### ISSUE TITLE
Feature request: import with entire icon

### ISSUE THREAD

**Issue by elado** [wmira/react-icons-kit#8]
current:

```js
import Icon from 'react-icons-kit';
import { drop } from 'react-icons-kit/ikons/drop';       

<Icon icon={drop} />
```

suggested:

```js
import DropIcon from 'react-icons-kit/ikons/drop';       

<DropIcon />
```

Essentially remove the `export const iconName =` and use `export default` that has `Icon` built in.

**Comment by wmira** [comment]
@elado  this can be accomplished via a module that you use to return icons. Please see the updated documentation on http://wmira.github.io/react-icons-kit/index.html#/
